# Add these dependencies to your Cargo.toml for the Advanced Predictive MEV Engine v2

[dependencies]
# Core async runtime
tokio = { version = "1.35", features = ["full"] }
async-trait = "0.1"

# Ethereum
ethers = "2.0"

# Machine Learning & Math
ndarray = { version = "0.15", features = ["serde"] }
ndarray-rand = "0.14"
tract-onnx = { version = "0.21", optional = true }
linfa = "0.7"  # ML algorithms
linfa-trees = "0.7"  # Random forests
smartcore = "0.3"  # Additional ML algorithms

# Numerical computing
nalgebra = "0.32"
statrs = "0.16"  # Statistical functions
rand = "0.8"
rand_distr = "0.4"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"

# Logging & Monitoring
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
metrics = "0.21"
prometheus = "0.13"

# Time handling
chrono = "0.4"

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Database (for experience replay)
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "chrono"] }
redis = { version = "0.24", features = ["tokio-comp", "connection-manager"] }

# Performance
parking_lot = "0.12"  # Faster mutexes
dashmap = "5.5"  # Concurrent hashmap
crossbeam = "0.8"  # Lock-free data structures
rayon = "1.8"  # Data parallelism

# SIMD operations
packed_simd_2 = "0.3"
simdeez = "1.0"

# Memory management
mimalloc = { version = "0.1", default-features = false }
jemalloc-sys = { version = "0.5", optional = true }

# Compression (for model storage)
zstd = "0.13"
lz4 = "1.24"

# HTTP client (for model downloading)
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }

# Feature engineering
ta = "0.5"  # Technical analysis indicators
num-traits = "0.2"
num-derive = "0.4"

# Testing
criterion = { version = "0.5", features = ["html_reports"] }
proptest = "1.4"
quickcheck = "1.0"

[features]
default = ["onnx", "parallel"]
onnx = ["tract-onnx"]
parallel = ["rayon"]
cuda = []  # For GPU acceleration
jemalloc = ["jemalloc-sys"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.bench]
inherits = "release"
debug = true