patterns:
  - name: "Unprotected Ether Withdrawal"
    type: "access_control"
    priority: 4
    signatures:
      - "withdraw(uint256)"
      - "withdrawAll()"
      - "emergencyWithdraw()"
    conditions:
      - "no_access_control"
      - "transfers_ether"
    exploit_template:
      calldata: "0x3ccfd60b"  # withdraw() selector
    confidence_weight: 0.9

  - name: "Reentrancy via External Call"
    type: "reentrancy"
    priority: 4
    opcodes: ["CALL", "SSTORE"]
    conditions:
      - "external_call_before_state_change"
    confidence_weight: 0.85

  - name: "Integer Overflow in Balance Calculation"
    type: "integer_overflow"
    priority: 3
    signatures:
      - "deposit(uint256)"
      - "mint(uint256)"
      - "increaseBal(uint256)"
    conditions:
      - "unchecked_arithmetic"
      - "uint256_addition"
    confidence_weight: 0.7

  - name: "Delegatecall to Untrusted Contract"
    type: "delegate_call"
    priority: 4
    opcodes: ["DELEGATECALL"]
    conditions:
      - "user_controlled_target"
    confidence_weight: 0.95

  - name: "Flash Loan Attack Vector"
    type: "flash_loan_attack"
    priority: 4
    signatures:
      - "flashLoan(address,uint256,bytes)"
      - "flashBorrow(address,uint256)"
    conditions:
      - "price_dependency"
      - "same_block_price_update"
    confidence_weight: 0.8

  - name: "Price Oracle Manipulation"
    type: "oracle_manipulation"
    priority: 3
    signatures:
      - "getPrice(address)"
      - "updatePrice(address,uint256)"
    conditions:
      - "single_source_oracle"
      - "manipulable_liquidity"
    confidence_weight: 0.75

  - name: "Unprotected Selfdestruct"
    type: "self_destruct"
    priority: 4
    opcodes: ["SELFDESTRUCT"]
    signatures:
      - "destroy()"
      - "kill()"
    conditions:
      - "accessible_by_anyone"
    exploit_template:
      calldata: "0x41c0e1b5"  # Common kill() selector
    confidence_weight: 1.0

  - name: "Storage Collision via Delegatecall"
    type: "uninitialized_storage"
    priority: 3
    opcodes: ["DELEGATECALL", "SLOAD", "SSTORE"]
    conditions:
      - "proxy_pattern"
      - "storage_layout_mismatch"
    confidence_weight: 0.8

  - name: "Front-Running Opportunity"
    type: "front_running"
    priority: 2
    signatures:
      - "claim()"
      - "claimReward()"
      - "buyToken(uint256)"
    conditions:
      - "predictable_outcome"
      - "no_commit_reveal"
    confidence_weight: 0.6

  - name: "Timestamp Dependency"
    type: "timestamp_dependence"
    priority: 2
    opcodes: ["TIMESTAMP"]
    conditions:
      - "timestamp_in_condition"
      - "financial_logic"
    confidence_weight: 0.5